name: Test CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: make dev

      - name: Validate code format
        run: make check

      - name: Run tests
        run: make test

      - name: Build
        run: make build
