name: Build Go binaries for supported platforms and publish them as GitHub release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22.x'

      - name: Install dependencies
        run: make dev

      - name: Build all
        run: make build-all

      - name: Upload built binaries
        uses: actions/upload-artifact@v4
        with:
          name: Go binaries
          path: build/*

      - name: Create a GitHub release
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          files: build/*